# Generated by Django 4.0.6 on 2022-07-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('Humidity', models.CharField(blank=True, max_length=10, null=True)),
                ('pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('lightInt', models.CharField(blank=True, max_length=10, null=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
