# Generated by Django 4.0.6 on 2022-07-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='altitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
